// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiyLdt2ZSHy9U1AWDmUzndMXDAGT3zHuI',
    appId: '1:718965389417:web:009e8fad6b0ed376f0caf8',
    messagingSenderId: '718965389417',
    projectId: 'journal-trend-63175',
    authDomain: 'journal-trend-63175.firebaseapp.com',
    storageBucket: 'journal-trend-63175.firebasestorage.app',
    measurementId: 'G-4JCDDQEBQR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWoKz2Y3pDpkC7991Db7NmrWtz1MJDpxc',
    appId: '1:718965389417:android:0324b0691b14af58f0caf8',
    messagingSenderId: '718965389417',
    projectId: 'journal-trend-63175',
    storageBucket: 'journal-trend-63175.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtivqBkIKuGf6RqTmj50zbk2IIUf8AhJo',
    appId: '1:718965389417:ios:ef517fa4c9324dd8f0caf8',
    messagingSenderId: '718965389417',
    projectId: 'journal-trend-63175',
    storageBucket: 'journal-trend-63175.firebasestorage.app',
    iosBundleId: 'com.example.prm393Lab2Se192044',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtivqBkIKuGf6RqTmj50zbk2IIUf8AhJo',
    appId: '1:718965389417:ios:ef517fa4c9324dd8f0caf8',
    messagingSenderId: '718965389417',
    projectId: 'journal-trend-63175',
    storageBucket: 'journal-trend-63175.firebasestorage.app',
    iosBundleId: 'com.example.prm393Lab2Se192044',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiyLdt2ZSHy9U1AWDmUzndMXDAGT3zHuI',
    appId: '1:718965389417:web:6ca9cb5d2ee5d949f0caf8',
    messagingSenderId: '718965389417',
    projectId: 'journal-trend-63175',
    authDomain: 'journal-trend-63175.firebaseapp.com',
    storageBucket: 'journal-trend-63175.firebasestorage.app',
    measurementId: 'G-NY58QK9QVE',
  );
}
