// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDe2xymq6UzfbcMSk_cAuut_O0mKw_YW3w',
    appId: '1:703569163237:web:717cda3bea40c733c4f50c',
    messagingSenderId: '703569163237',
    projectId: 'prm393-lab2-se192044',
    authDomain: 'prm393-lab2-se192044.firebaseapp.com',
    storageBucket: 'prm393-lab2-se192044.firebasestorage.app',
    measurementId: 'G-HT392JHVG9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATnwmO1v3WZ5pI-nbiPc9WqRo_e1NUmb4',
    appId: '1:703569163237:android:bb1fe8ff7f64a5b8c4f50c',
    messagingSenderId: '703569163237',
    projectId: 'prm393-lab2-se192044',
    storageBucket: 'prm393-lab2-se192044.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzoy4p2-bajx_Qf0FHHrvm6qqZO9fCAQI',
    appId: '1:703569163237:ios:c69d9f6b34270300c4f50c',
    messagingSenderId: '703569163237',
    projectId: 'prm393-lab2-se192044',
    storageBucket: 'prm393-lab2-se192044.firebasestorage.app',
    iosBundleId: 'com.example.prm393Lab2Se192044',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzoy4p2-bajx_Qf0FHHrvm6qqZO9fCAQI',
    appId: '1:703569163237:ios:c69d9f6b34270300c4f50c',
    messagingSenderId: '703569163237',
    projectId: 'prm393-lab2-se192044',
    storageBucket: 'prm393-lab2-se192044.firebasestorage.app',
    iosBundleId: 'com.example.prm393Lab2Se192044',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDe2xymq6UzfbcMSk_cAuut_O0mKw_YW3w',
    appId: '1:703569163237:web:adea7def435a2ff4c4f50c',
    messagingSenderId: '703569163237',
    projectId: 'prm393-lab2-se192044',
    authDomain: 'prm393-lab2-se192044.firebaseapp.com',
    storageBucket: 'prm393-lab2-se192044.firebasestorage.app',
    measurementId: 'G-2PQ57WLV1E',
  );
}
